export { default as Home } from './Home/index.vue'
export { default as Order } from './Order/index.vue'
export { default as Menu } from './Menu/index.vue'
export { default as Setting } from './Setting/index.vue'
export { default as AddOrder } from './AddOrder/index.vue'
export { default as CreateOrderDetail } from './CreateOrderDetail/index.vue'
export { default as OrderByAuction } from './OrderByAuction/index.vue'
